### PR TITLE
Added More Info & Privacy Policy pages

### PR DESCRIPTION
**Pull request by theperu**
As we discussed yesterday I tried to write some Privacy Policy for our app, of course I am not a lawyer and I don't know if this are fine or not. I tried to be safe and write sections that should also cover future changes (see Service Providers, Log Data and Information Collection and Use). 
I also add the version of the app and collaborators (this page is not ready yet but we will update it in the future)

### CODE REVIEW

**Review by FedericoBruzzone — APPROVED** [review]
LGTM👍

**Comment by theperu** [comment]
Not sure on why this is failing now since there isn't much new with the latest commit. It looks like it is SDK related and we also had a warning before, I would leave it to you to decide what is best to do

**Comment by FedericoBruzzone** [comment]
> Not sure on why this is failing now since there isn't much new with the latest commit. It looks like it is SDK related and we also had a warning before, I would leave it to you to decide what is best to do

```
Dependency 'androidx.core:core:1.10.1' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':app' is 'android-31'

Dependency 'androidx.annotation:annotation-experimental:1.3.0' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':app' is 'android-31'
```
You are right. The problem refers to the SDK version in gradle project for android. 

You can fix this by modifying our project’s build.gradle file ([Android folder](https://github.com/RIP-Comm/sossoldi/tree/main/android)) and adding the ‘compileSdkVersion’ field.

Once you have updated the ‘compileSdkVersion’, you should also update any other dependencies that require a minimum SDK version of 33 or higher to ensure that our app functions correctly.

After doing this you can run: 
1. `git add --all` 
2. `git commit --amend` 
3. `git push --force` 
to update the failed commit.

**Comment by theperu** [comment]
I changed compileSdkVersion but it seems that we still have problems, I am not able to really figure it out though. When I use it on my machine it seems fine and I don't have issues so it's also quite hard to understand what to change

**Comment by FedericoBruzzone** [comment]
> I changed compileSdkVersion but it seems that we still have problems, I am not able to really figure it out though. When I use it on my machine it seems fine and I don't have issues so it's also quite hard to understand what to change

I understand, let's try this last test and if it doesn't work, we'll go back and put back what was written: `flutter.compileSdkVersion`

 Try to update in this way: ext.kotlin_version = '<latest-version>'

**Comment by FedericoBruzzone** [comment]
LGTM :+1:

**Pull request merged**
