### PR TITLE
Start implementation of general settings

### PR DESCRIPTION
**Pull request by 0xbaggi**
As suggested in #70, I added a new section (general setting) in the page settings, which will have general settings like light/dark mode and currency selector. I haven't started to implement the page because it hasn't been defined on Figma yet.
image

### CODE REVIEW

**Review by FedericoBruzzone — APPROVED** [review]

**Review by FedericoBruzzone — APPROVED** [review]

**Comment by theperu** [comment]
Hi @0xbaggi ! Since I haven't heard back from the guy who was working on #70 if you want you can start implementing that part in the general settings. Personally I wouldn't wait for the figma since this is a small part of the app and there shouldn't be many problems with it. 
For the dark mode I remember that @napitek already tried something but we can implement it in the future.

**Comment by 0xbaggi** [comment]
I added some static buttons in the general settings page, their functionalities have yet to be implemented.

- Appearance to enable/disable dark mode
- Currency to select your preferred currency
- Language to select the app’s default language

[Screen_recording_20230913_232758.webm](https://github.com/RIP-Comm/sossoldi/assets/39710037/a8f9c9b5-fee3-47d5-8fdf-c70e0c4fb446)

**Review by theperu — CHANGES_REQUESTED** [review]
Hi I would remove the language picker (or we can keep the code and just avoid displaying it) for now since we won't support other languages before version 1.0.
I see that the check failed with this message:

> The current Dart SDK version is 2.18.0.
> Because sossoldi depends on country_flags >=2.1.0 which requires SDK version >=3.0.0 <4.0.0, version solving failed.

We should probably look into that, we might think about using the emojis for the flags (Ex. 🇮🇹, 🇬🇧, 🇩🇪, 🇫🇷) instead of something external.

**Comment by 0xbaggi** [comment]
I removed the library, replaced the flags with the relative emojis and hid the language setting for future versions.
The hidden part is made with emoji without the library(not currently visible because commented):

image

**Review by theperu — APPROVED** [review]

**Review by theperu — APPROVED** [review]
Looks good and the check passed, @mikev-cw if you are ok with that I think we can merge this

**Comment by mikev-cw** [comment]
@theperu if you already checked, it's enough. Let's merge!

**Pull request merged**
