### PR TITLE
Transactions working implementation + minor fix

### PR DESCRIPTION
**Pull request by lucaantonelli**
Now transactions works fine, insert/update/delete and income/expense/transfer.
The only missing implementation is for recurring payment.

Known Issue: A glitch when disposing the transaction modal on delete

### CODE REVIEW

**Comment by theperu** [comment]
While checking this I noticed a couple of things:
1. It looks like we don't have any categories from the add transaction page which to me it doesn't seem right
2. When I try to add a transfer between two accounts and I come back to the dashboard I see an error
Not sure if this is specifically related to this PR but we should look into that.
Also if I close and reopen the app the error for the account transfer goes away kinda like it wasn't saved. Am I doing something wrong? 
I uploaded a video of my tests [here](https://drive.google.com/file/d/17gInj70WTZjmdFKu67atihm1V5G2P47q/view?usp=share_link)

**Comment by lucaantonelli** [comment]
> While checking this I noticed a couple of things:
> 
> 1. It looks like we don't have any categories from the add transaction page which to me it doesn't seem right
> 2. When I try to add a transfer between two accounts and I come back to the dashboard I see an error
>    Not sure if this is specifically related to this PR but we should look into that.
>    Also if I close and reopen the app the error for the account transfer goes away kinda like it wasn't saved. Am I doing something wrong?
>    I uploaded a video of my tests [here](https://drive.google.com/file/d/17gInj70WTZjmdFKu67atihm1V5G2P47q/view?usp=share_link)

Have you tried removing app data or delete the app and reinstall? It seems you could have an old version of the "fake data" in the db, otherwise if it continues to not work can you share the console log?

**Comment by theperu** [comment]
You are right, it looks like something went wrong with the iOS emulator and I didn't notice. I tried again and it looks fine now. Great work! To me it looks like we can merge this if you are not planning to implement the recurring payment right away

**Comment by mikev-cw** [comment]
I confirm it's working on Android too. Super cool, let's merge!

**Pull request merged**
